schemaVersion: 1.0
name: InitWebsite
description: Installs httpd and creates simple website
phases:
  - name: build
    steps:
      - name: SetupWebsite
        action: ExecuteBash
        inputs:
          commands:
            - |
              TIME=$(date)
              yum -y update
              yum -y install httpd
    
              cat <<EOT >> /var/www/html/index.html
              <h1>Hello from EC2!</h1>
              <h3>Image build time: ${TIME}</h3>
              EOT
              
              systemctl enable httpd
              systemctl start httpd