CREATE USER proxy_user WITH PASSWORD '${PROXY_PASSWORD}';

GRANT SELECT,INSERT,UPDATE,DELETE ON users TO proxy_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to proxy_user;

CREATE USER app_user;
GRANT rds_iam TO app_user;

GRANT SELECT,INSERT,UPDATE,DELETE ON users TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to app_user;
